### ISSUE TITLE
component(Cocina): validar que items existe antes de pintar data

### ISSUE THREAD

**Issue by Danielalab** [Estefaniamr1/LIM013-fe-burger-queen#39]
https://github.com/Estefaniamr1/LIM013-fe-burger-queen/blob/d450e89923a27717fbc319a4e89a6351dc8b7e30/my-app/src/cocina.js#L20-L37

Revisando el mensaje de error decidí ver si items tenía data para ser filtrada en la función `getName` por lo ucal hice un `console.log(items)` dentro de la función.

```js
    const getName = (idElement) => {
        console.log(items);
        const getItem =  items.filter((item)=>item.id===idElement)[0];
        return (getItem.nombre);
    }
```

Y al revisar la console me indica que es un `array` vacío (ver imagen :arrow_down:) por lo cual cuando aplicamos el método `filter` obtenemos un `array` vacío y al intentar acceder al elemento en la posición `[0]` nos devuelve `undefined` porque no existen elementos en el `array` filtrado.

![items-vacio](https://user-images.githubusercontent.com/32286663/104202707-408ee200-53f9-11eb-9993-2e75894d1b9b.png)

Algo que podrían hacer es validar que existe data en `items` antes de pintar la lista de productos de la orden.
Pueden colocar una condición que pregunte si  `items` tiene elementos pinte cada elemento caso contrario que muestre un mensaje de cargando utilizando un operador ternario (ver código :arrow_down: ).

```js
 const listOrders = orders.map((order)=> 
    <div key={order.id}>
        <span>{order.cliente}</span>
        <ul className="listItems-order">
            {  items.length > 0 ?
                 order.list.map((element)=>
                            <li key={element.id}>
                                <span>{element.cantidad}</span>
                                <span>{getName(element.id)}</span>
                            </li>)
                 : 'loading' }
        </ul>
        <span>{order.total}</span>
    </div>
    )
```
@Estefaniamr1 @LauraJimenezB

**Comment by LauraJimenezB** [comment]
Dani, con el ternario se muestra y ya no sale error. No entendemos muy bien el proceso de porque el ternario ayuda a mostrar los items, si nos podrias explicar un poco porfa. Gracias!
